### PR TITLE
Added waterfall documentation

### PR DESCRIPTION
**Pull request by akmaldju**

### CODE REVIEW

**Comment by izairiabdlatif** [comment]
@akmaldju  My comments:

- All images are not shown. Pls fix it
- Why is there an extra thick line after Diagram Design / Configuration title?
 
- Category shows a name for a certain category Open Value shows the existing amount before the current category is applied Value reflects the amount after the current category is applied StepValue presents the difference between current value and initial value
Amend to: Category shows a name for a certain category. Open Value shows the existing amount before the current category is applied. Value reflects the amount after the current category is applied. StepValue presents the difference between current value and initial value

> add in full stop between sentences, which makes all the difference in clarity. There is a difference between "Let's eat, grandma" and "Let's eat grandma" LOL!

- The optional bindings are color binding which binds the color of the nodes and Display Value that shows the difference between amounts before a category was applied and after.
Amend to:
The optional bindings are: 
- ```color``` binding which binds the color of the nodes 
- ```Display Value``` that shows the difference between amounts before a category was applied and after

- Sample data download here.
Link is broken. I can't find the sample data at the three different locations stated in the document

- This dataset shows all finance costs, expenses, incomes and net revenue of a company for a given period of time
Amend to: This dataset shows all finance costs, expenses, **income** and net revenue of a company for a given period of time (there's no plural version of the word "income")

**Comment by akmaldju** [comment]
@izairiabdlatif Based on your review, fixed pictures and links and other minor improvements

**Comment by izairiabdlatif** [comment]
@akmaldju  My comments based on the latest file:

- ```Start Value``` shows the existing amount before the current category is applied. This value will always be 0 for the first and last columns and is equal to 
Amend to: ......```End Value``` of **previous** category...

- 'End Value' is a sup of 'Value' and 'Start Value'
Do you mean that ```End Value``` is a sub of ```Value```?

- Display Label that shows the difference between amounts before a category was applied and after
Amend to: ```Display Label``` that shows the difference between amounts before and after a category is applied 

- Current dataset displays a person's savings based on one's salary and spendings
Amend to: Current dataset displays a person's savings based on one's salary and **spending**

-----

Apart from that, all sample datasets are accessible.
All reference images load beautifully! (^^)b

**Comment by akmaldju** [comment]
@izairiabdlatif Thank you, made changes accordingly

**Pull request merged**
